[2022-08-19 22:53:53,296] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-08-19T22:53:50.319542+00:00 [queued]>
[2022-08-19 22:53:53,302] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop manual__2022-08-19T22:53:50.319542+00:00 [queued]>
[2022-08-19 22:53:53,303] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 22:53:53,304] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-19 22:53:53,305] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 22:53:53,312] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): run_after_loop> on 2022-08-19 22:53:50.319542+00:00
[2022-08-19 22:53:53,316] {standard_task_runner.py:52} INFO - Started process 119 to run task
[2022-08-19 22:53:53,318] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'manual__2022-08-19T22:53:50.319542+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpfdkh1uzq', '--error-file', '/tmp/tmphov7mehj']
[2022-08-19 22:53:53,319] {standard_task_runner.py:80} INFO - Job 14: Subtask run_after_loop
[2022-08-19 22:53:53,362] {task_command.py:371} INFO - Running <TaskInstance: example_bash_operator.run_after_loop manual__2022-08-19T22:53:50.319542+00:00 [running]> on host fd7a784b9251
[2022-08-19 22:53:53,404] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T22:53:50.319542+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T22:53:50.319542+00:00
[2022-08-19 22:53:53,405] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-19 22:53:53,406] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2022-08-19 22:53:53,413] {subprocess.py:85} INFO - Output:
[2022-08-19 22:53:53,415] {subprocess.py:92} INFO - 1
[2022-08-19 22:53:53,416] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-19 22:53:53,440] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20220819T225350, start_date=20220819T225353, end_date=20220819T225353
[2022-08-19 22:53:53,491] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 22:53:53,518] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
