[2022-08-19 22:53:51,697] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-08-19T22:53:50.319542+00:00 [queued]>
[2022-08-19 22:53:51,707] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2022-08-19T22:53:50.319542+00:00 [queued]>
[2022-08-19 22:53:51,708] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 22:53:51,708] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-19 22:53:51,709] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-19 22:53:51,720] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): also_run_this> on 2022-08-19 22:53:50.319542+00:00
[2022-08-19 22:53:51,726] {standard_task_runner.py:52} INFO - Started process 112 to run task
[2022-08-19 22:53:51,730] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2022-08-19T22:53:50.319542+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmp28an7fwc', '--error-file', '/tmp/tmp3zatrjw4']
[2022-08-19 22:53:51,732] {standard_task_runner.py:80} INFO - Job 13: Subtask also_run_this
[2022-08-19 22:53:51,810] {task_command.py:371} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2022-08-19T22:53:50.319542+00:00 [running]> on host fd7a784b9251
[2022-08-19 22:53:51,868] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T22:53:50.319542+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-19T22:53:50.319542+00:00
[2022-08-19 22:53:51,869] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-19 22:53:51,871] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2022-08-19T22:53:50.319542+00:00 | dag_run=<DagRun example_bash_operator @ 2022-08-19 22:53:50.319542+00:00: manual__2022-08-19T22:53:50.319542+00:00, externally triggered: True>"']
[2022-08-19 22:53:51,881] {subprocess.py:85} INFO - Output:
[2022-08-19 22:53:51,883] {subprocess.py:92} INFO - run_id=manual__2022-08-19T22:53:50.319542+00:00 | dag_run=<DagRun example_bash_operator @ 2022-08-19 22:53:50.319542+00:00: manual__2022-08-19T22:53:50.319542+00:00, externally triggered: True>
[2022-08-19 22:53:51,884] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-19 22:53:51,908] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20220819T225350, start_date=20220819T225351, end_date=20220819T225351
[2022-08-19 22:53:51,941] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-19 22:53:51,963] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
